using System.Net.Http.Json;
using Microsoft.AspNetCore.Mvc.Testing;
using NBomber.CSharp;
using PlantDiseaseRecognition.WebApi.Api.Controllers;
using PlantDiseaseRecognition.WebApi.Engine.Rust.Models;

namespace PlantDiseaseRecognition.WebApi.LoadTesting;

public class LoadTests : IClassFixture<WebApplicationFactory<Program>>
{
	private readonly WebApplicationFactory<Program> _factory;

	public LoadTests(WebApplicationFactory<Program> factory)
	{
		_factory = factory;
	}

	[Fact]
	public async Task LoadTest_Inference_Gpu()
	{
		await using var factory = new TestWebApplicationFactory(DeviceType.Gpu);
		var client = factory.CreateClient();

		var scenario = Scenario.Create("inference_gpu", async context =>
		{
			var image = "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAgGBgcGBQgHBwcJCQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2wBDAQkJCQwLDBgNDRgyIRwhMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjIyMjL/wAARCADgAOADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwDx0ffqYg5BzTUhJOafJGw6VBsIRxmmKSxxUiqQnIpqkAms7FXEIxTtuFzSFssBTip3AUWC4wHPanqAT0p/TjFLsbGQKLBcQjHagCnq3BBFIKQ0GKMYpaSgAJphFOoI4qhEZYDtUbc05qaKZJJbSeWwzzW7bXkbKBtrnehq/ZyYIzQgNwqsgyFpnkqoOQKdE4KilYZ6nFaJCZHFbh27CpJLcRt60n3GG01IZCG3EZFNom5Xlzt9KmilKIOaXypbtyqRk/SomheNtrAgilYLj/MLuOtXC4EBGKggQDk0tzKoQgVLQ7mDdZ+0MagJNXJF3SE1GYxmocR3I0ABqRgu4ZqGEFjUkiHNaAJME2cVS2cmrvksVphiIpWFcz87XH1q9FFJLgqMipLTTWuJRx3rtLDRobezJlTmiwXOQGnzEbtvFRSSeSNrcGvR4bS0eDGzmuR1PTo2uWCrxmiwXOe8zJp4qxd2qW5Xiq4qJFxFpCKdSGpKG4oI4pcUEcVQiBqaBT2poFMkNuacjGM0ChhmmirGpZ3O7AzWqsXnAAVzluxRq2bO5fcNp6VoiWjai0kmBnK9Kha0/wBGY45ra0uV7hRFnO7ipb+y+yv5bDihszZS0d4LRd0pxxWdeOklw7L0JqaVPNJjQdKh+zlc57UriK5+VTWbcuxar10/l8Vnlg5oGNA3CjyzUsS/NU20UWGMXTmUcClFixNdNJbqOMCiG2VnHApgY0WnnYARQukMXzjjNdOtoA+MVd+zIkWcDpTEjEtLGOFfuDNXY1ZpAvao2f8Ae4A71o2kG4hsUFgLQgccCuf1aMREnHNdiFwcYrl9fQYzQSzi9QBdgc9KppgrVu8JDYxVEggYqJocRrSbWoi3SvjnrVm2szO3NWvsi25BqLFEkNoFA3DOajvYAqnAxV2OYPgelNuxuU0WAxFUdxUbY3cCrphNMW2LN0osBXK4HSkxkdKvvakAcU1bY+laFlNFO6tK0jLkENjFReRjtUibk6UEM7LQL2GFgGAJ9a6i5WG+TduUH615dZysrZ3EVrHVp4hhSx/GgzZt3loluSwZc/WsC4uMMwBpk2pSzL82RVOQlhnNAIjlk3nk5pqrTCpzUyDFAx8a4NS4pimpAKAOpniIbpT7aPDgmrMqhzkUzIQe9MC4FUnNMnfKbRTI2JQc1CzESfN60xIZHaEybiO9a1sVSRVqBJY9nA5xTFEjPvB4oLNeTywDzzXMavavOSFGa1RHcSPw3FaNtZoy/vRk0Es80vdHdVLFayo7IseRXqGtWcXknYO1ccLXaxwKTQRKMFt5K5AqpcbpJNuO9dAsIC/MKrGzDS5A70rFGfHZsmDjrUkluTxitgxKoUEU/wCybuQOKLAYqWGV6VNFp/J4rXWNUGCKlSIc8UWAw5LPPamCxIHSt8wAHJFG2PGMUDuc29mc9KQWTYPFdCYUY9KR4kVeBQS2c0lpIr9KsMhXrWg8TKc1VlBJ5oJM+cMR8ooBO0A1bMW4cUx7V15oHErKuTU6R06O3c1MY2TrSGyHZinqtOClqUEKcGghnWbxUchyM1AHOakBzxVFEsTkKKYz/NyKt28IZRRLaj1piQ2OVQOlWYbhVTG2mQWisetWHtVjbGaCxVuQOi4q5byl84NVUtwwq7bQBc89qCWY+sMwU/N2rnohuJroNbiPY1iwLgUmCDaOlTRwL1xULn5qnRjs/CkMbMi7hS9F4qPazt0NWPLIXmi4FfblqkBCijviplti+Dg0XArncaVUzV5oABURXFArkYQAUx1BqRs+lREE0CK8qAiqUsJNaflkmneQMdKBmEY2U1atIfNbDdPerctuPSqzOYj8opMaLr2AVcrj8Kqvb8ciprfUMja/61fihS4YHIxSGc7LbuvIBAqqQytzXcS6ajwAJgtWHe6Uyc7SKB8poLB3xQExIBWq1oysMDg1NHaxDDMtacpnzIpRnZT23OOKuNAjP8q8VItmxxtFOwXKcKyKelXggePc/WtCC0REzIOcVXuIw3+r4FIfMVoyo6GmS3bR520bCh5qpdSoooE2Ub64llOCOKzT8lW5pgwOKzJZCc1LBIlzk1KjjpWd5j561ZhOetIdjVtVVgSamkjBHFVbeVY+DVt5028UAQJbndnFXk2xrVaCTc2KlmU44oERM+SaQJmkVDmpNrAcUxDDGKjKDNWArHrTjEB1oAgWIUjJirIUAVG65oHcqNHmqUkaZINawSqcsAJJxSeo0zEniKtuWrNpqRgAUnmpZo8Ais2WJQ2cc0rFI67RdSEt0fMPy4rYvLeK5jJTnivPrS5aGUYOBXd6TfwvEofkkUjRNF/aG2rtyRwaSdQo2bcE1oW0aRTSmQgDPGaZIY7i9QIQR7VucoWNgGhDtSyNHCxGBxWhKfs0WwdqxZQZZCSSKRQS3gb5RxVWSYqcU2aMIc7qrvcoByRmkA6R9wrKu1JzzUtxqAXOMVTN2JTikBUkBVTVB8mtKWMtVZoTSKiUwvNWYhijy8GpkSgZPCu6rLRkr1qCNSKtxnPWgQ23iYNmpptwA61dt0XA6UsyKfSgRnAkU8MalaMCmgDNAhUNPPIpygVJtBFAFYinKmalMXNOVcCgCBo8VWkUc1oMMiqciHcaAuZk6D0rMnTk1tzRHHSs+aH2oGmY0oK8itPT7x48fMagkt9wqKIFXxU2LUj1/WrSRwDbDOetQaJZGH57kYkB4qC21lpVxvq19oY/MTWxmXL5wzk54rDvbpYl+Q81JeXvB5rn7q43seaQxZr6V8isueZ/M+apixzVW4BZs0gIpCHHWiFSrUzkGpEYZFIC+oBWo2Ct0qaAqUxT9iJ2oKRntGQaVWUHrV4iNu1Qvbr1AosAI6jvzUyBuoHFV0RVOSKu28iNxRYRat3AwDVlo94yKou6x8irlrcq4waLCI5IT6VXKFTzWizA1XdQaLCI0GelTRxsDyKSNQDVtcYosBFs4pjRt2qzxTGOKLAVtjDrTTGDUzNTlXigTKEsQFZ80XWtqZM1Rlj4oEYc6FRwKpxxkOSwrXnSqUgAosO5b0q6lIGSa6SK6YqASaxNKQeUDgdK0jJtcDFWULdueaynf5uav3MgYGsid8E0iiYuoFV5pPSoC7H1p6AFfmPNICEsSelOQHNWFhU0jxFegpAXLYdOasSxFhwazI2dT0NXoZm/iFCBERidD1NOXd0OatmZCOcUiFGPaqAr+WSOlLGDG1XH8tRywFVnkiJwGFAibAlFOj/dEe9QpNHH1YU4yJIQQ3SgRo4JUGomBpY7hSAM1MMMKBECA5qwufWk4U0olAoAfg0xqf5oxVeSUZoAkAzUqrxVVJM1aVxikAyRc1Ulj4q4zioZmG2gLGLcLjNZc55rWuWGTWLcyDdVJCN2y3RwjYO1TMZGOSOaqm8jtEwx6Cs241+NQcNz9aRsrGnO0gBqgzAn56yZdf3j7xqhLq7E8NTJOkLQD+KoZLmBT96uaOpOx+9Ub3EjHOaCWdONQjTo1I2qKf4q5UyyetHmSetKxN2dSNTUHrTm1bA4Nct5j+tIZXPenYabOifVz/epF1p1PBrndzE9acNxoC5uz61NKQuefrVc6lNHIFY4NZu1/vg9KUE3ByfvUAa/2+Ujc5+Wj+0blCDFyO/NVIbC7vR5MXUc9KJGNt+5Y/OvBoA14dYkGMnmtGDXGJALVyQJ60hldT1qQPQItQjkUEtThcxE8NXDwXzgAbqtDUWXB3UAdiZ1x1qFp0J61zi6mSPvUn9oEt96gDq4WVsYNWn+VBt61ztnqAwMmtaOVpBkHimhFuMFvvVWvXKKdtVrq9e3H3qw7rVnfI3UmUiW7uWAJrBlu3eQg+tPlvHdiCao7suTSux2H3uqPOTtJrKLyM/LHFCgjGOasxws6/drSxDkRqKGWp/srDsaa0YXqaB3IVXBqXIppX0pp3Z6UBceSKTNM59KctAh2aXFLg4zim78daAQ4CnA0wPml3UDHmTAI9ansrV7mQImQx9KrggRs3cdBWp4fvTbTLdSIMqfumgDtYHtNE0FJJkVp+QfWvO7iY3OoTTAYVjkCruv6pJqF08ikhT/AAjpVJsRRIV5J60gBWxT8bhTGzgHFPjkAGCaQERypp28nvSyc9KjBoAkEhHepBKR3qLFRsSDQBcW8aPoa1bLXsDac8VzoGetSRx7DkGgTOgvtR84celYzzHmmPM2OlQmUntSZSAzZahWyahds80I2OtSMji4NaEEg4FZ61Mj4Nb2MrGm8qhazZmDNRJITUQDE0guSrjFGRmm8gU0Ak0DuPODTeAakCEikMdAxwYbTUZQP1p6qc0roR92kxkax4OBT/LUDPenIwA5601sk8dKAFiXe3ParLkImBVXf5ZAHenFy4oAQfM1OfIxRHwakYA0AKp3LUEibWzU6DbSSgMDSAjRsjFO27Tn1qFflapmbcBQAvWkK0q0E8UARMMGnh+BTGNRluaBMlZ6hZqQk00mpZSFJqJ2pzHAqB3yakZo/ZiBUIUiQCtjG9fu1VNrmUV0EJqxEsW41YFsAucVMLYJyDSPKwG3bSMylIgBxUJGG4q08ZY5xSCL1p2ZVyEEgUEmrHlik8sE0WHdEHNORuMN1qx5aqM+lNSITyBidtSx8yIGtZHO5c4oc+WuD1rZE620O0KGxWJct50xPTmlYLoiRGckmpRxxUqEbMYqJ05zQFx2eOKQOQaQEjtS4zSC5IZOBSg5FV+9SowximMY/WnRjNDKCc0qvjjFACk4qNnpXeoCc0APLZpppBQaQmITTSaUionbFSykEpyvFV8EsKkDljgipjFgKRzmpGdBFKhHWnkqTxWLHMw71YS4PXNbmLNZF3CkMANV4bkHHNW1lBpoQxoQBUXlAirTDcKjB2jFWBWaKozHirRbJpNuRUsCoQcYpgOzpViQYBqDbuNSA1pS/FQslWvKxTGSgZADt4oLZpzpzTNuKkYUbqQikIpDEakBNKTSgCgYZ4pjvinMQKrSNk0wJN2aXFNjGanC8UAR4xTCeTUjHFRMcUgGO2BUBfJoleoQTmpZSLKrnpViBgzhT61XifHWn25/f596ko//2Q==";
			var request = new InferenceController.InferRequest(image);
			var content = JsonContent.Create(request);
			var result = await client.PostAsync("/api/v1/inference", content);
			return result.IsSuccessStatusCode
				? Response.Ok()
				: Response.Fail(
					statusCode: result.StatusCode.ToString()
				);
		})
			.WithWarmUpDuration(TimeSpan.FromSeconds(30))
			.WithLoadSimulations(
				Simulation.Inject(
					rate: 5,
					interval: TimeSpan.FromSeconds(1),
					during: TimeSpan.FromSeconds(60)
				)
			);

		var stats = NBomberRunner
			.RegisterScenarios(scenario)
			.WithReportFolder("load_test_results")
			.Run();
	}
}
