use serde_json;
use std::{collections::HashMap, env, fs, path::Path};

use burn_onnx::ModelGen;

fn main() {
    generate_model();
    generate_metadata();
}

fn generate_model() {
    ModelGen::new()
        .input("../models/effnet_b0.onnx")
        .out_dir("./models")
        .run_from_script();
}

fn generate_metadata() {
    let json_str = include_str!("../models/effnet_b0.json");
    let root: serde_json::Value = serde_json::from_str(json_str).unwrap();

    let classes: Vec<String> = serde_json::from_value(root["classes"].clone()).unwrap();
    let input_size: Vec<usize> = serde_json::from_value(root["input_size"].clone()).unwrap();

    let classes_str: String = classes
        .iter()
        .map(|name| format!("    {:?},", name))
        .collect::<Vec<_>>()
        .join("\n");

    let input_shape = format!(
        "[{}, {}, {}, {}]",
        input_size[0], input_size[1], input_size[2], input_size[3]
    );

    fs::write(
        Path::new(&env::var("OUT_DIR").unwrap()).join("metadata.rs"),
        format!(
            r#"
// AUTOGENERATED BY build.rs
pub struct Metadata {{
    pub classes: &'static [&'static str],
		pub input_shape: [usize; 4],	
}}

impl Metadata {{    
		const fn new() -> Self {{
        Self {{
            classes: &[
{classes_str}
            ],
						input_shape: {input_shape},
        }}
    }}

    pub fn class_name(&self, idx: usize) -> Option<&'static str> {{
        self.classes.get(idx).copied()
    }}
}}

pub static METADATA: Metadata = Metadata::new();
"#
        ),
    )
    .unwrap();
}
